### PR TITLE
Add operation not pending error

### PR DESCRIPTION
**Pull request by matthias-geuchen**
**Reason for this PR:**
- operations that are no longer pending should not be modified anymore
- transactions failing due to the corresponding operation not being pending should state so in their response

### CODE REVIEW

**Review by bastihav — APPROVED** [review]
The errors are added for matriculation, as those transactions can act as an approve for a operation/transaction, right?
If that is not the case, why did you not add them for other transactions?

**Comment by NikoBergemann** [comment]
> The errors are added for matriculation, as those transactions can act as an approve for a operation/transaction, right?
> If that is not the case, why did you not add them for other transactions?

Yes, we do have to also add the Error to AdmissionHandling, and OperationHandling - you should get the same error for approve/rejectOperaiton, if it is no longer pending

**Review by dhelmert — CHANGES_REQUESTED** [review]
We get this error on two occasions;
Firstly, when trying to Approve/Reject an operation that is not in PENDING.
Secondly, when trying to execute a Transaction which is not in PENDING.

The first is an error which we give back to the user, he made a mistake in the ApproveOperation that he sent us.
The second is an internal server error on our side, since we should not be executing a transaction which has a corresponding operation in FINISHED or REJECTED state. We specifically check for that, which means we have an internal server error.

Is is possible to use the newly "ApprovalDenied" and "RejectionDenied" state in the first case, and the new error in the second? Then we can treat the new error as an internal server error, and the "-Denied" errors as a bad request (or whatever 4XX code is fitting)

**Comment by matthias-geuchen** [comment]
> > The errors are added for matriculation, as those transactions can act as an approve for a operation/transaction, right?
> > If that is not the case, why did you not add them for other transactions?
> 
> Yes, we do have to also add the Error to AdmissionHandling, and OperationHandling - you should get the same error for approve/rejectOperaiton, if it is no longer pending

Added the error to addAdmission and dropAdmission

**Review by NikoBergemann — APPROVED** [review]
Very nice, I especially like how we now have multiple errors for distinct cases

**Comment by matthias-geuchen** [comment]
> We get this error on two occasions;
> Firstly, when trying to Approve/Reject an operation that is not in PENDING.
> Secondly, when trying to execute a Transaction which is not in PENDING.
> 
> The first is an error which we give back to the user, he made a mistake in the ApproveOperation that he sent us.
> The second is an internal server error on our side, since we should not be executing a transaction which has a corresponding operation in FINISHED or REJECTED state. We specifically check for that, which means we have an internal server error.
> 
> Is is possible to use the newly "ApprovalDenied" and "RejectionDenied" state in the first case, and the new error in the second? Then we can treat the new error as an internal server error, and the "-Denied" errors as a bad request (or whatever 4XX code is fitting)

Using the same error would not allow us to distinguish between missing access rights and a prohibiting operation status. Two new errors were introduced.

**Review by dhelmert — APPROVED** [review]

**Review by RBeierling — APPROVED** [review]

**Review by bastihav — APPROVED** [review]

**Pull request merged**
